IDENTIFICATION DIVISION.
PROGRAM-ID. Factorial-Steve28.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 n BINARY-LONG.
01 i BINARY-LONG.
01 prod BINARY-LONG VALUE 1.

PROCEDURE DIVISION.
DISPLAY "Input a Number!".
ACCEPT n.
PERFORM VARYING i FROM 1 BY 1 UNTIL i > n
    MULTIPLY prod BY i GIVING prod
END-PERFORM
DISPLAY n "! = " prod. 
STOP RUN.
